language: node_js
node_js:
  - "8"
before_script:
  - npm install
  - psql -c 'create database "test";' -U postgres
  - psql -c 'CREATE USER "test" WITH SUPERUSER PASSWORD 'test';' -U postgres
script: npm test
services:
  - postgresql
